// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Infrastructure.Data;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251204201506_LocalCreateV0.2.1")]
    partial class LocalCreateV021
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Server.Features.Buddies.Buddy", b =>
                {
                    b.Property<int>("RequesterId")
                        .HasColumnType("int");

                    b.Property<int>("AddresseeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("RequesterId", "AddresseeId");

                    b.HasIndex("AddresseeId");

                    b.ToTable("Buddys");
                });

            modelBuilder.Entity("Server.Features.Chats.JourneyMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("JourneyId")
                        .HasColumnType("int");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("JourneyId");

                    b.HasIndex("SenderId");

                    b.ToTable("JourneyMessages");
                });

            modelBuilder.Entity("Server.Features.DangerousPlaces.DangerousPlace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("GPS")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PlaceType")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ReportedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReportedById");

                    b.ToTable("DangerousPlaces");
                });

            modelBuilder.Entity("Server.Features.Journeys.Journey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EndId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("StartId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EndId");

                    b.HasIndex("StartId");

                    b.ToTable("Journeys");
                });

            modelBuilder.Entity("Server.Features.Journeys.JourneyParticipant", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("JourneyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("UserId", "JourneyId");

                    b.HasIndex("JourneyId");

                    b.ToTable("JourneyParticipants");
                });

            modelBuilder.Entity("Server.Features.Journeys.Place", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CentreGPS")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("District")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Places");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CentreGPS = "51.4416,5.4697",
                            City = "Eindhoven",
                            District = "Centrum"
                        },
                        new
                        {
                            Id = 2,
                            CentreGPS = "51.4480,5.4485",
                            City = "Eindhoven",
                            District = "Strijp"
                        },
                        new
                        {
                            Id = 3,
                            CentreGPS = "51.4147,5.4688",
                            City = "Eindhoven",
                            District = "Gestel"
                        },
                        new
                        {
                            Id = 4,
                            CentreGPS = "51.4220,5.4938",
                            City = "Eindhoven",
                            District = "Stratum"
                        },
                        new
                        {
                            Id = 5,
                            CentreGPS = "51.4440,5.5075",
                            City = "Eindhoven",
                            District = "Tongelre"
                        },
                        new
                        {
                            Id = 6,
                            CentreGPS = "51.4582,5.4779",
                            City = "Eindhoven",
                            District = "Woensel-Zuid"
                        },
                        new
                        {
                            Id = 7,
                            CentreGPS = "51.4886,5.4672",
                            City = "Eindhoven",
                            District = "Woensel-Noord"
                        },
                        new
                        {
                            Id = 8,
                            CentreGPS = "51.4186,5.4028",
                            City = "Veldhoven",
                            District = "Centrum"
                        },
                        new
                        {
                            Id = 9,
                            CentreGPS = "51.5075,5.3953",
                            City = "Best"
                        },
                        new
                        {
                            Id = 10,
                            CentreGPS = "51.5096,5.4904",
                            City = "Son en Breugel"
                        },
                        new
                        {
                            Id = 11,
                            CentreGPS = "51.3915,5.4590",
                            City = "Waalre"
                        },
                        new
                        {
                            Id = 12,
                            CentreGPS = "51.4215,5.5590",
                            City = "Geldrop"
                        },
                        new
                        {
                            Id = 13,
                            CentreGPS = "51.4750,5.5480",
                            City = "Nuenen"
                        },
                        new
                        {
                            Id = 14,
                            CentreGPS = "51.4792,5.6570",
                            City = "Helmond"
                        },
                        new
                        {
                            Id = 15,
                            CentreGPS = "51.4439,5.6204",
                            City = "Mierlo"
                        },
                        new
                        {
                            Id = 16,
                            CentreGPS = "51.5052,5.3137",
                            City = "Oirschot"
                        },
                        new
                        {
                            Id = 17,
                            CentreGPS = "51.3831,5.5728",
                            City = "Heeze"
                        },
                        new
                        {
                            Id = 18,
                            CentreGPS = "51.3502,5.5492",
                            City = "Leende"
                        },
                        new
                        {
                            Id = 19,
                            CentreGPS = "51.3141,5.6284",
                            City = "Maarheeze"
                        },
                        new
                        {
                            Id = 20,
                            CentreGPS = "51.3012,5.6028",
                            City = "Soerendonk"
                        },
                        new
                        {
                            Id = 21,
                            CentreGPS = "51.4310,5.2886",
                            City = "Vessem"
                        },
                        new
                        {
                            Id = 22,
                            CentreGPS = "51.4099,5.3340",
                            City = "Knegsel"
                        },
                        new
                        {
                            Id = 23,
                            CentreGPS = "51.4306,5.3822",
                            City = "Wintelre"
                        },
                        new
                        {
                            Id = 24,
                            CentreGPS = "51.3503,5.3818",
                            City = "Riethoven"
                        },
                        new
                        {
                            Id = 25,
                            CentreGPS = "51.3846,5.3704",
                            City = "Steensel"
                        },
                        new
                        {
                            Id = 26,
                            CentreGPS = "51.3340,5.4138",
                            City = "Westerhoven"
                        },
                        new
                        {
                            Id = 27,
                            CentreGPS = "51.5106,5.3501",
                            City = "Spoordonk"
                        },
                        new
                        {
                            Id = 28,
                            CentreGPS = "51.5157,5.4813",
                            City = "Breugel"
                        },
                        new
                        {
                            Id = 29,
                            CentreGPS = "51.5033,5.4132",
                            City = "Aarle"
                        },
                        new
                        {
                            Id = 30,
                            CentreGPS = "51.4278,5.5322",
                            City = "Zesgehuchten"
                        },
                        new
                        {
                            Id = 31,
                            CentreGPS = "51.4624,5.5622",
                            City = "Eeneind"
                        },
                        new
                        {
                            Id = 32,
                            CentreGPS = "51.3646,5.2577",
                            City = "Hapert"
                        },
                        new
                        {
                            Id = 33,
                            CentreGPS = "51.3800,5.2560",
                            City = "Hoogeloon"
                        },
                        new
                        {
                            Id = 34,
                            CentreGPS = "51.3686,5.2196",
                            City = "Bladel"
                        },
                        new
                        {
                            Id = 35,
                            CentreGPS = "51.4094,5.2338",
                            City = "Casteren"
                        },
                        new
                        {
                            Id = 36,
                            CentreGPS = "51.4850,5.5400",
                            City = "Gerwen"
                        },
                        new
                        {
                            Id = 37,
                            CentreGPS = "51.4254,5.3648",
                            City = "Oerle"
                        },
                        new
                        {
                            Id = 38,
                            CentreGPS = "51.4203,5.4155",
                            City = "Veldhoven",
                            District = "Heikant"
                        },
                        new
                        {
                            Id = 39,
                            CentreGPS = "51.3967,5.4642",
                            City = "Aalst"
                        });
                });

            modelBuilder.Entity("Server.Features.Journeys.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("JourneyId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<int>("RatingValue")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("JourneyId", "UserId")
                        .IsUnique();

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("Server.Features.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phonenumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Server.Features.Users.UserVerification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserVerifications");
                });

            modelBuilder.Entity("Server.Features.Buddies.Buddy", b =>
                {
                    b.HasOne("Server.Features.Users.User", "Addressee")
                        .WithMany()
                        .HasForeignKey("AddresseeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Features.Users.User", "Requester")
                        .WithMany()
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Addressee");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("Server.Features.Chats.JourneyMessage", b =>
                {
                    b.HasOne("Server.Features.Journeys.Journey", "Journey")
                        .WithMany("Messages")
                        .HasForeignKey("JourneyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Features.Users.User", "Sender")
                        .WithMany("SentMessages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Journey");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Server.Features.DangerousPlaces.DangerousPlace", b =>
                {
                    b.HasOne("Server.Features.Users.User", "ReportedBy")
                        .WithMany("Reports")
                        .HasForeignKey("ReportedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReportedBy");
                });

            modelBuilder.Entity("Server.Features.Journeys.Journey", b =>
                {
                    b.HasOne("Server.Features.Journeys.Place", "End")
                        .WithMany()
                        .HasForeignKey("EndId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Features.Journeys.Place", "Start")
                        .WithMany()
                        .HasForeignKey("StartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("End");

                    b.Navigation("Start");
                });

            modelBuilder.Entity("Server.Features.Journeys.JourneyParticipant", b =>
                {
                    b.HasOne("Server.Features.Journeys.Journey", "Journey")
                        .WithMany("Participants")
                        .HasForeignKey("JourneyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Features.Users.User", "User")
                        .WithMany("JourneyParticipations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Journey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Server.Features.Journeys.Rating", b =>
                {
                    b.HasOne("Server.Features.Journeys.Journey", "Journey")
                        .WithMany("Ratings")
                        .HasForeignKey("JourneyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Features.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Journey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Server.Features.Users.UserVerification", b =>
                {
                    b.HasOne("Server.Features.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Server.Features.Journeys.Journey", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Participants");

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("Server.Features.Users.User", b =>
                {
                    b.Navigation("JourneyParticipations");

                    b.Navigation("Reports");

                    b.Navigation("SentMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
