// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Data;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Server.Models.DangerousPlace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("GPS")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PlaceType")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ReportedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReportedById");

                    b.ToTable("DangerousPlace");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Very dark street, watch out!",
                            GPS = "52.370216,4.895168",
                            PlaceType = 3,
                            ReportedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReportedById = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Lots of garbage here",
                            GPS = "51.924420,4.477733",
                            PlaceType = 2,
                            ReportedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReportedById = 2
                        });
                });

            modelBuilder.Entity("Server.Models.Journey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EndGPS")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FinishedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("OwnedBy")
                        .HasColumnType("int");

                    b.Property<string>("StartGPS")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("OwnedBy");

                    b.ToTable("Journeys");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 10, 26, 17, 14, 46, 37, DateTimeKind.Utc).AddTicks(4482),
                            EndGPS = "51.924420,4.477733",
                            FinishedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnedBy = 1,
                            StartGPS = "52.370216,4.895168"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 10, 26, 17, 14, 46, 37, DateTimeKind.Utc).AddTicks(4578),
                            EndGPS = "51.441642,5.469722",
                            FinishedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnedBy = 2,
                            StartGPS = "52.090737,5.121420"
                        });
                });

            modelBuilder.Entity("Server.Models.JourneyMessages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("JourneyId")
                        .HasColumnType("int");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("JourneyId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Hi Bob!",
                            JourneyId = 1,
                            SenderId = 1,
                            SentAt = new DateTime(2025, 10, 26, 17, 14, 46, 37, DateTimeKind.Utc).AddTicks(5592)
                        },
                        new
                        {
                            Id = 2,
                            Content = "Hey Alice!",
                            JourneyId = 1,
                            SenderId = 2,
                            SentAt = new DateTime(2025, 10, 26, 17, 14, 46, 37, DateTimeKind.Utc).AddTicks(5659)
                        },
                        new
                        {
                            Id = 3,
                            Content = "Hello Charlie!",
                            JourneyId = 2,
                            SenderId = 2,
                            SentAt = new DateTime(2025, 10, 26, 17, 14, 46, 37, DateTimeKind.Utc).AddTicks(5660)
                        });
                });

            modelBuilder.Entity("Server.Models.JourneyParticipants", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("JourneyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("UserId", "JourneyId");

                    b.HasIndex("JourneyId");

                    b.ToTable("JourneyParticipants");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            JourneyId = 1,
                            JoinedAt = new DateTime(2025, 10, 26, 17, 14, 46, 37, DateTimeKind.Utc).AddTicks(5037)
                        },
                        new
                        {
                            UserId = 2,
                            JourneyId = 1,
                            JoinedAt = new DateTime(2025, 10, 26, 17, 14, 46, 37, DateTimeKind.Utc).AddTicks(5114)
                        },
                        new
                        {
                            UserId = 2,
                            JourneyId = 2,
                            JoinedAt = new DateTime(2025, 10, 26, 17, 14, 46, 37, DateTimeKind.Utc).AddTicks(5115)
                        },
                        new
                        {
                            UserId = 3,
                            JourneyId = 2,
                            JoinedAt = new DateTime(2025, 10, 26, 17, 14, 46, 37, DateTimeKind.Utc).AddTicks(5116)
                        });
                });

            modelBuilder.Entity("Server.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phonenumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 10, 26, 17, 14, 46, 37, DateTimeKind.Utc).AddTicks(830),
                            Email = "alice@test.com",
                            PasswordHash = "hashed1",
                            Phonenumber = "0612345678",
                            Username = "Alice"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 10, 26, 17, 14, 46, 37, DateTimeKind.Utc).AddTicks(935),
                            Email = "bob@test.com",
                            PasswordHash = "hashed2",
                            Phonenumber = "0687654321",
                            Username = "Bob"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 10, 26, 17, 14, 46, 37, DateTimeKind.Utc).AddTicks(936),
                            Email = "charlie@test.com",
                            PasswordHash = "hashed3",
                            Phonenumber = "0678901234",
                            Username = "Charlie"
                        });
                });

            modelBuilder.Entity("Server.Models.DangerousPlace", b =>
                {
                    b.HasOne("Server.Models.User", "ReportedBy")
                        .WithMany("Reports")
                        .HasForeignKey("ReportedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReportedBy");
                });

            modelBuilder.Entity("Server.Models.Journey", b =>
                {
                    b.HasOne("Server.Models.User", "Owner")
                        .WithMany("OwnedJourneys")
                        .HasForeignKey("OwnedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Server.Models.JourneyMessages", b =>
                {
                    b.HasOne("Server.Models.Journey", "Journey")
                        .WithMany("Messages")
                        .HasForeignKey("JourneyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Models.User", "Sender")
                        .WithMany("SentMessages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Journey");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Server.Models.JourneyParticipants", b =>
                {
                    b.HasOne("Server.Models.Journey", "Journey")
                        .WithMany("Participants")
                        .HasForeignKey("JourneyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Models.User", "User")
                        .WithMany("JourneyParticipations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Journey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Server.Models.Journey", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("Server.Models.User", b =>
                {
                    b.Navigation("JourneyParticipations");

                    b.Navigation("OwnedJourneys");

                    b.Navigation("Reports");

                    b.Navigation("SentMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
