// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Data;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Server.Models.Buddy", b =>
                {
                    b.Property<int>("RequesterId")
                        .HasColumnType("int");

                    b.Property<int>("AddresseeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("RequesterId", "AddresseeId");

                    b.HasIndex("AddresseeId");

                    b.ToTable("Buddys");

                    b.HasData(
                        new
                        {
                            RequesterId = 1,
                            AddresseeId = 2,
                            RequestedAt = new DateTime(2026, 1, 7, 18, 27, 53, 941, DateTimeKind.Utc).AddTicks(7077),
                            Status = 1
                        },
                        new
                        {
                            RequesterId = 1,
                            AddresseeId = 3,
                            RequestedAt = new DateTime(2026, 1, 7, 18, 27, 53, 941, DateTimeKind.Utc).AddTicks(7277),
                            Status = 1
                        },
                        new
                        {
                            RequesterId = 4,
                            AddresseeId = 1,
                            RequestedAt = new DateTime(2026, 1, 7, 18, 27, 53, 941, DateTimeKind.Utc).AddTicks(7279),
                            Status = 1
                        },
                        new
                        {
                            RequesterId = 2,
                            AddresseeId = 4,
                            RequestedAt = new DateTime(2026, 1, 7, 18, 27, 53, 941, DateTimeKind.Utc).AddTicks(7279),
                            Status = 1
                        },
                        new
                        {
                            RequesterId = 5,
                            AddresseeId = 2,
                            RequestedAt = new DateTime(2026, 1, 7, 18, 27, 53, 941, DateTimeKind.Utc).AddTicks(7280),
                            Status = 1
                        },
                        new
                        {
                            RequesterId = 3,
                            AddresseeId = 4,
                            RequestedAt = new DateTime(2026, 1, 7, 18, 27, 53, 941, DateTimeKind.Utc).AddTicks(7281),
                            Status = 0
                        });
                });

            modelBuilder.Entity("Server.Models.DangerousPlace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("GPS")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PlaceType")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ReportedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReportedById");

                    b.ToTable("DangerousPlace");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Very dark street, watch out!",
                            GPS = "52.370216,4.895168",
                            PlaceType = 3,
                            ReportedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReportedById = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Lots of garbage here",
                            GPS = "51.924420,4.477733",
                            PlaceType = 2,
                            ReportedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReportedById = 2
                        });
                });

            modelBuilder.Entity("Server.Models.Journey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EndGPS")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("StartGPS")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Journeys");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 7, 18, 27, 53, 941, DateTimeKind.Utc).AddTicks(4565),
                            EndGPS = "51.924420,4.477733",
                            StartGPS = "52.370216,4.895168"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 7, 18, 27, 53, 941, DateTimeKind.Utc).AddTicks(4780),
                            EndGPS = "51.441642,5.469722",
                            StartGPS = "52.090737,5.121420"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 6, 18, 27, 53, 941, DateTimeKind.Utc).AddTicks(4781),
                            EndGPS = "444556677",
                            StartGPS = "111222333"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 6, 18, 27, 53, 941, DateTimeKind.Utc).AddTicks(4812),
                            EndGPS = "111222333",
                            FinishedAt = new DateTime(2026, 1, 7, 18, 27, 53, 941, DateTimeKind.Utc).AddTicks(4813),
                            StartGPS = "444556677"
                        });
                });

            modelBuilder.Entity("Server.Models.JourneyMessages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("JourneyId")
                        .HasColumnType("int");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("JourneyId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Hi Bob!",
                            JourneyId = 1,
                            SenderId = 1,
                            SentAt = new DateTime(2026, 1, 7, 18, 27, 53, 941, DateTimeKind.Utc).AddTicks(6062)
                        },
                        new
                        {
                            Id = 2,
                            Content = "Hey Alice!",
                            JourneyId = 1,
                            SenderId = 2,
                            SentAt = new DateTime(2026, 1, 7, 18, 27, 53, 941, DateTimeKind.Utc).AddTicks(6132)
                        },
                        new
                        {
                            Id = 3,
                            Content = "Hello Charlie!",
                            JourneyId = 1,
                            SenderId = 2,
                            SentAt = new DateTime(2026, 1, 7, 18, 27, 53, 941, DateTimeKind.Utc).AddTicks(6133)
                        },
                        new
                        {
                            Id = 4,
                            Content = "Hi Bob!",
                            JourneyId = 2,
                            SenderId = 1,
                            SentAt = new DateTime(2026, 1, 7, 18, 27, 53, 941, DateTimeKind.Utc).AddTicks(6134)
                        },
                        new
                        {
                            Id = 5,
                            Content = "Hey Alice!",
                            JourneyId = 2,
                            SenderId = 2,
                            SentAt = new DateTime(2026, 1, 7, 18, 27, 53, 941, DateTimeKind.Utc).AddTicks(6135)
                        },
                        new
                        {
                            Id = 6,
                            Content = "Hello Charlie!",
                            JourneyId = 2,
                            SenderId = 2,
                            SentAt = new DateTime(2026, 1, 7, 18, 27, 53, 941, DateTimeKind.Utc).AddTicks(6147)
                        });
                });

            modelBuilder.Entity("Server.Models.JourneyParticipants", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("JourneyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("UserId", "JourneyId");

                    b.HasIndex("JourneyId");

                    b.ToTable("JourneyParticipants");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            JourneyId = 1,
                            JoinedAt = new DateTime(2026, 1, 7, 18, 27, 53, 941, DateTimeKind.Utc).AddTicks(5442),
                            Role = 0
                        },
                        new
                        {
                            UserId = 2,
                            JourneyId = 1,
                            JoinedAt = new DateTime(2026, 1, 7, 18, 27, 53, 941, DateTimeKind.Utc).AddTicks(5513),
                            Role = 1
                        },
                        new
                        {
                            UserId = 3,
                            JourneyId = 1,
                            JoinedAt = new DateTime(2026, 1, 7, 18, 27, 53, 941, DateTimeKind.Utc).AddTicks(5514),
                            Role = 1
                        },
                        new
                        {
                            UserId = 4,
                            JourneyId = 1,
                            JoinedAt = new DateTime(2026, 1, 7, 18, 27, 53, 941, DateTimeKind.Utc).AddTicks(5515),
                            Role = 1
                        },
                        new
                        {
                            UserId = 2,
                            JourneyId = 2,
                            JoinedAt = new DateTime(2026, 1, 7, 18, 27, 53, 941, DateTimeKind.Utc).AddTicks(5516),
                            Role = 0
                        },
                        new
                        {
                            UserId = 1,
                            JourneyId = 2,
                            JoinedAt = new DateTime(2026, 1, 7, 18, 27, 53, 941, DateTimeKind.Utc).AddTicks(5517),
                            Role = 1
                        },
                        new
                        {
                            UserId = 4,
                            JourneyId = 2,
                            JoinedAt = new DateTime(2026, 1, 7, 18, 27, 53, 941, DateTimeKind.Utc).AddTicks(5518),
                            Role = 1
                        },
                        new
                        {
                            UserId = 5,
                            JourneyId = 2,
                            JoinedAt = new DateTime(2026, 1, 7, 18, 27, 53, 941, DateTimeKind.Utc).AddTicks(5519),
                            Role = 1
                        },
                        new
                        {
                            UserId = 4,
                            JourneyId = 3,
                            JoinedAt = new DateTime(2026, 1, 6, 18, 27, 53, 941, DateTimeKind.Utc).AddTicks(5520),
                            Role = 0
                        },
                        new
                        {
                            UserId = 4,
                            JourneyId = 4,
                            JoinedAt = new DateTime(2026, 1, 6, 18, 27, 53, 941, DateTimeKind.Utc).AddTicks(5522),
                            Role = 0
                        });
                });

            modelBuilder.Entity("Server.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phonenumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 7, 18, 27, 53, 941, DateTimeKind.Utc).AddTicks(118),
                            Email = "alice@test.com",
                            PasswordHash = "Btd5kOga0bCQboFgEC27wQXmHO/7+ycka95ivGi4EXXAEOj303ehnFqmaGr3+rHi",
                            Phonenumber = "0600000000",
                            Username = "Alice"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 7, 18, 27, 53, 941, DateTimeKind.Utc).AddTicks(250),
                            Email = "bob@test.com",
                            PasswordHash = "DbjdjPrHA2CdSDtuDrpWqWbAcxPQIoxHxNz73a0P8CFWd/Sg55yo/+FTDbdsxtdL",
                            Phonenumber = "0611111111",
                            Username = "Bob"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 7, 18, 27, 53, 941, DateTimeKind.Utc).AddTicks(251),
                            Email = "charlie@test.com",
                            PasswordHash = "JULrd1HVJ17woc2HEqrjpsOx6Ac+z60MWP0lmhPlKB7HupLEX7ANdCZeqTABaBOO",
                            Phonenumber = "0622222222",
                            Username = "Charlie"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 7, 18, 27, 53, 941, DateTimeKind.Utc).AddTicks(252),
                            Email = "Joseph@test.com",
                            PasswordHash = "JULrd1HVJ17woc2HEqrjpsOx6Ac+z60MWP0lmhPlKB7HupLEX7ANdCZeqTABaBOO",
                            Phonenumber = "0633333333",
                            Username = "Joseph"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 7, 18, 27, 53, 941, DateTimeKind.Utc).AddTicks(253),
                            Email = "Diana@test.com",
                            PasswordHash = "JULrd1HVJ17woc2HEqrjpsOx6Ac+z60MWP0lmhPlKB7HupLEX7ANdCZeqTABaBOO",
                            Phonenumber = "0644444444",
                            Username = "Diana"
                        });
                });

            modelBuilder.Entity("Server.Models.Buddy", b =>
                {
                    b.HasOne("Server.Models.User", "Addressee")
                        .WithMany()
                        .HasForeignKey("AddresseeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Models.User", "Requester")
                        .WithMany()
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Addressee");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("Server.Models.DangerousPlace", b =>
                {
                    b.HasOne("Server.Models.User", "ReportedBy")
                        .WithMany("Reports")
                        .HasForeignKey("ReportedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReportedBy");
                });

            modelBuilder.Entity("Server.Models.Journey", b =>
                {
                    b.HasOne("Server.Models.User", null)
                        .WithMany("OwnedJourneys")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Server.Models.JourneyMessages", b =>
                {
                    b.HasOne("Server.Models.Journey", "Journey")
                        .WithMany("Messages")
                        .HasForeignKey("JourneyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Models.User", "Sender")
                        .WithMany("SentMessages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Journey");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Server.Models.JourneyParticipants", b =>
                {
                    b.HasOne("Server.Models.Journey", "Journey")
                        .WithMany("Participants")
                        .HasForeignKey("JourneyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Models.User", "User")
                        .WithMany("JourneyParticipations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Journey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Server.Models.Journey", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("Server.Models.User", b =>
                {
                    b.Navigation("JourneyParticipations");

                    b.Navigation("OwnedJourneys");

                    b.Navigation("Reports");

                    b.Navigation("SentMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
